apiVersion: apps/v1
kind: Deployment
metadata:
	name: addressbook-deployment
	labels:
		app: addressbook
spec:
	replicas: 1
	selector:
		matchLabels:
			app: addressbook
	template:
		metadata:
			labels:
				app: addressbook
		spec:
			containers:
				- name: addressbook
				  image: aditya3328/addressbook:latest
				  ports:
				  	- containerPort: 8080
